var mongoose = require('mongoose');

var transactionSchema = new mongoose.Schema({
  leadName: String,
  contactId: Number,
  leadSource: String,
  type: String,
  streetAddress: String,
  city: String,
  state: String,
  zip: String,
  MLS_Id: String,
  boardId: String,
  agentName: String,
  MLS_AgentId: String,
  MLS_OfficeId: String,
  boomtownAgentId: String,
  boomtownOfficeId: String,
  status: String,
  originalListPrice: Number,
  closedSalePrice: Number,
  listingDate: Date,
  expirationDate: Date,
  acceptPendingDate: Date,
  closeDate: Date,
  lenderName: String,
  boomtownLenderId: String,
  loanAmount: Number,
  GCI: Number,
  CommSplitAgent: Number,
  CommSplitBroker: Number,
  brokerFee: Number,
  cap: Number,
  referralFee: Number,
  ISA_Fee: Number,
  transactionCoordFee: Number,
  miscFee: Number,
  mainPhoto: String,
});

module.exports = mongoose.model('Transaction', transactionSchema);
